### **Exercici 1:**  

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades.  
Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np

Array_1 = np.array([1,2,3,4,5,6,2,4,3,5])
Array_2 = np.array([[2,3,4,3,6,7], [3,5,6,2,7,8]])

def resum_array(array):
    if array.ndim > 1:
        print('Error !. Existeix más d\'una dimensió.')
    else:
        print("Resumen estadístico:\n")
        print('L\'array te '+ str(array.size) + ' elements.\nEl valor maxim es de ' + str(np.max(array)) + ' i el minim de ' + str(np.min(array)) + '.\n'
    + 'La mitja de l\'array es ' + str(np.mean(array)) + ' i la mitjana ' + str(np.median(array)) + '.\nLa dessviació standard es ' + str(np.std(array)) + '.\n')


In [2]:
resum_array(Array_1)

Resumen estadístico:

L'array te 10 elements.
El valor maxim es de 6 i el minim de 1.
La mitja de l'array es 3.5 i la mitjana 3.5.
La dessviació standard es 1.5.



In [3]:
resum_array(Array_2)

Error !. Existeix más d'una dimensió.


### **Exercici 2**  
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


In [4]:
import numpy as np

def quadrat (n):
    array = np.random.randint(0,100,(n,n))
    return array

n = int(input('Introdueix el nombre de dades per banda del quadrat: '))
quadrat(n)

Introdueix el nombre de dades per banda del quadrat: 5


array([[61, 22, 68,  5, 24],
       [82, 46, 76, 87, 99],
       [ 0, 18, 84, 98, 42],
       [70,  1, 38, 46, 32],
       [76, 30, 44, 62, 93]])

### **Exercici 3**  

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [5]:
import numpy as np

def fun_tabla(n2, n3):
    array = np.random.randint(0,100,(n2,n3))
    print('La taula te ' + str(array.shape[0]) + ' filas y ' + str(array.shape[1]) + ' columnas.\n')
    return array
  
n2 = int(input('Introdueix un num.:\n'))
n3 = int(input('Introdueix el segon num.:\n'))

tabla = fun_tabla(n2, n3)
print(tabla)
print('\n')

i = 0
for i in range(n2):
    print('Fila ' + str(i) + ' = ' + str(np.sum(tabla[i])))
for j in range(n3):
    print('Columna ' + str(i) + ' = ' + str(np.sum(tabla[:,j])))

Introdueix un num.:
4
Introdueix el segon num.:
6
La taula te 4 filas y 6 columnas.

[[85 90  1 52 44 26]
 [61 29 82 45 51 48]
 [41 49 44 94 60 95]
 [51 96 23 90  9 12]]


Fila 0 = 298
Fila 1 = 316
Fila 2 = 383
Fila 3 = 281
Columna 3 = 238
Columna 3 = 264
Columna 3 = 150
Columna 3 = 281
Columna 3 = 164
Columna 3 = 181


### **Exercici 4**  

Implementa manualment una funció que calculi el coeficient de correlació.  
Informa-te'n sobre els seus usos i interpretació.

*El coeficient de correlació de Pearson és un índex que mesura el grau de relació de dues variables quantitatives i contínues.
A diferència de la covariància, la correlació de Pearson és independent de l'escala de mesura de les variables.*  
*Hi ha una relació directa en tractar-se d'1 (quan una variable augmenta, l'altra també), mentre que hi haurà una relació inversa en tractar-se de -1 (quan una variable augmenta l'altra disminueix).
En el cas de 0 (o proper a aquest valor) no hi ha relació lineal, encara que hi pot haver algun altre tipus de relació no lineal.*  
*La fórmula de Pearson és el càlcul de la covariància entre les variables, dividida pel producte de les seves desviacions estàndard.*  


In [6]:
import pandas as pd
import numpy as np
abandono = pd.read_csv('abandono.csv')
abandono.head(3)

id  edad  abandono             viajes            departamento  \
0   1    41         1      Travel_Rarely                   Sales   
1   2    49         0  Travel_Frequently  Research & Development   
2   4    37         1      Travel_Rarely  Research & Development   

   distancia_casa      educacion        carrera satisfaccion_entorno  \
0               1  Universitaria  Life Sciences                Media   
1               8     Secundaria  Life Sciences                 Alta   
2               2     Secundaria          Other             Muy_Alta   

  implicacion  ...  satisfaccion_companeros nivel_acciones anos_experiencia  \
0        Alta  ...                     Baja              0                8   
1       Media  ...                 Muy_Alta              1               10   
2       Media  ...                    Media              0                7   

  num_formaciones_ult_ano  anos_compania  anos_desde_ult_promocion  \
0                       0              6                         0   
1                       3             10                         1   
2                       3              0                         0   

  anos_con_manager_actual  salario_ano impacto_abandono scoring_abandono  
0                       5        71916        14670,864         0,328125  
1                       7        61560         12558,24     0,0620155039  
2                       0        25080          4037,88     0,2926829268  

[3 rows x 29 columns]

In [7]:
edad = abandono['edad']
tiempo_empresa = abandono['anos_compania']

def pearson (una, otra):
    return np.corrcoef(una, otra)

round(pearson(edad, tiempo_empresa)[1,0], 5)

0.31131

In [8]:
nn = len(edad)
media_edad = np.mean(edad)
media_tiempo_empresa = np.mean(tiempo_empresa)
desv_edad = np.std(edad)
desv_tiempo_empresa = np.std(tiempo_empresa)

r = 0
for i in range(nn):
    r += ((1/nn) * (edad[i] - media_edad) * (tiempo_empresa[i] - media_tiempo_empresa)) / (desv_edad * desv_tiempo_empresa)

r_redond = round(r,5)
print(r_redond)

0.31131


*El coeficiente es positivo, luego a mayor edad, mayor tiempo en la empresa, pero al ser relativamente bajo, 
(El coeficiente se mueve entre 0 y +/- 1), entiendo que la correlación entre las dos variables no es muy alta.  
No es muy fiable*