### **Exercici 2**  
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


In [1]:
import numpy as np

def quadrat (n):
    array = np.random.randint(0,101,(n,n))
    return array

n = int(input('Introdueix el nombre de dades per banda del quadrat: '))
quadrat(n)

Introdueix el nombre de dades per banda del quadrat: 5


array([[ 6, 78, 10, 57, 66],
       [65, 86, 29, 32, 11],
       [59, 70, 92, 97, 14],
       [70,  7, 82, 65, 20],
       [94, 23, 48, 23, 92]])

### **Exercici 3**  

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [2]:
import numpy as np

def fun_tabla(n2, n3):
    array = np.random.randint(0,100,(n2,n3))
    print('La taula te ' + str(array.shape[0]) + ' filas y ' + str(array.shape[1]) + ' columnas.\n')
    i = 0
    for i in range(n2):
        print('Fila ' + str(i) + ' = ' + str(np.sum(array[i])))
    for j in range(n3):
        print('Columna ' + str(i) + ' = ' + str(np.sum(array[:,j])))
    return array

n2 = int(input('Introdueix un num.:\n'))
n3 = int(input('Introdueix el segon num.:\n'))

tabla = fun_tabla(n2, n3)
print('\n')
print(tabla)


Introdueix un num.:
5
Introdueix el segon num.:
3
La taula te 5 filas y 3 columnas.

Fila 0 = 113
Fila 1 = 209
Fila 2 = 250
Fila 3 = 126
Fila 4 = 88
Columna 4 = 247
Columna 4 = 174
Columna 4 = 365


[[ 8 14 91]
 [97 21 91]
 [70 90 90]
 [41 29 56]
 [31 20 37]]


### **Exercici 4**  

Implementa manualment una funció que calculi el coeficient de correlació.  
Informa-te'n sobre els seus usos i interpretació.

*El coeficient de correlació de Pearson és un índex que mesura el grau de relació de dues variables quantitatives i contínues.
A diferència de la covariància, la correlació de Pearson és independent de l'escala de mesura de les variables.*  
*Hi ha una relació directa en tractar-se d'1 (quan una variable augmenta, l'altra també), mentre que hi haurà una relació inversa en tractar-se de -1 (quan una variable augmenta l'altra disminueix).
En el cas de 0 (o proper a aquest valor) no hi ha relació lineal, encara que hi pot haver algun altre tipus de relació no lineal.*  
*La fórmula de Pearson és el càlcul de la covariància entre les variables, dividida pel producte de les seves desviacions estàndard.*  


In [6]:
import pandas as pd
import numpy as np
abandono = pd.read_csv('abandono.csv')
abandono.head(3)

id  edad  abandono             viajes            departamento  \
0   1    41         1      Travel_Rarely                   Sales   
1   2    49         0  Travel_Frequently  Research & Development   
2   4    37         1      Travel_Rarely  Research & Development   

   distancia_casa      educacion        carrera satisfaccion_entorno  \
0               1  Universitaria  Life Sciences                Media   
1               8     Secundaria  Life Sciences                 Alta   
2               2     Secundaria          Other             Muy_Alta   

  implicacion  ...  satisfaccion_companeros nivel_acciones anos_experiencia  \
0        Alta  ...                     Baja              0                8   
1       Media  ...                 Muy_Alta              1               10   
2       Media  ...                    Media              0                7   

  num_formaciones_ult_ano  anos_compania  anos_desde_ult_promocion  \
0                       0              6                         0   
1                       3             10                         1   
2                       3              0                         0   

  anos_con_manager_actual  salario_ano impacto_abandono scoring_abandono  
0                       5        71916        14670,864         0,328125  
1                       7        61560         12558,24     0,0620155039  
2                       0        25080          4037,88     0,2926829268  

[3 rows x 29 columns]

In [7]:
edad = abandono['edad']
tiempo_empresa = abandono['anos_compania']

def pearson (una, otra):
    return np.corrcoef(una, otra)

round(pearson(edad, tiempo_empresa)[1,0], 5)

0.31131

In [8]:
edad = abandono['edad']
tiempo_empresa = abandono['anos_compania']

def pearson(edad, tiempo_empresa):
    nn = len(edad)
    r = 0
    for i in range(nn):
        r += ((1/nn) * (edad[i] - np.mean(edad)) * (tiempo_empresa[i] - np.mean(tiempo_empresa))) / (np.std(edad) * np.std(tiempo_empresa))
    print(round(r,5))
    
pearson(edad, tiempo_empresa)


0.31131


*El coeficiente es positivo, luego a mayor edad, mayor tiempo en la empresa, pero al ser relativamente bajo, 
(El coeficiente se mueve entre 0 y +/- 1), entiendo que la correlación entre las dos variables no es muy alta.  
No es muy fiable*